"""minor changes2

Revision ID: 03b6663bc873
Revises: 80349efafc54
Create Date: 2024-09-18 15:33:10.471182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b6663bc873'
down_revision = '80349efafc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('body_bleached')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_bleached', sa.VARCHAR(length=750), nullable=True))

    # ### end Alembic commands ###
