"""minor changes1

Revision ID: 80349efafc54
Revises: 34a1292f2ea6
Create Date: 2024-09-18 15:29:29.886403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80349efafc54'
down_revision = '34a1292f2ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_bleached', sa.String(length=750), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('body_bleached')

    # ### end Alembic commands ###
